name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y build-essential libexpat-dev autoconf libtool

    - name: Build!
      run: make

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: xflasher
        path: out/bin/xflasher-ng
