name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    strategy:
      matrix:
        architecture: [x86_64, arm64]
        include:
          - architecture: x86_64
            runs-on: ubuntu-latest
          - architecture: arm64
            runs-on: ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y build-essential libexpat-dev autoconf libtool
    - name: Build!
      run: make
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: xflasher-${{ matrix.architecture }}
        path: out/bin/xflasher
